### ISSUE TITLE
Samples do not have the pyarch itself

### ISSUE THREAD

**Issue by prabhakar267** [jumpip/PyArch#18]
I was looking at the samples and to my amaze, i was not able to find the **pyarch** dependency in the any of the samples. 
I am a bit confused here, a person does need to install the **pyarch** library, right? 
Please help me out, I am new to all this hardware open source and if you could guide me how I could implement this on my local machine.
Thanks in advance :grinning:

**Comment by JeeveshN** [comment]
@prabhakar267 we wrote the samples before we had packaged **pyarch** so if u clone the repository and run the files directly u'll be able to use it.
We'll change the samples by evening today.

**Comment by JeeveshN** [comment]
@prabhakar267 The samples have been updated.

**Comment by prachi1210** [comment]
@prabhakar267 @JeeveshN 
Shall we close this issue?
